Feature/content type filters redesign
ONSdigital/dp-frontend-search-controller pull request #296
Opened 2024-04-04 12:38 UTC by StRhys

### What

This [ticket](https://trello.com/c/sk5rB5S1) was to bring the content type filters inline with the designs.

Checking and unchecking the tickboxes produces some weird behaviour though, such as

- On `/publications` checking all filters, starting with 'Statistical bulletins', will only filter to 'bulletins` and have 4514 rather than the expected 7475
- Checking 'Compendiums' doesn't do anything, in the chrome network tab, it's causing a 500 error
- Going to http://localhost:25000/publications?page=1&filter=article&filter=compendia is ok (minus filtering not working) but going to http://localhost:25000/publications?page=1&filter=compendia throws the 500 page

Looks like the api is only looking at the first filter query and ignoring the others but then works fine on `/search` 

### How to review

Pull this branch and run app make debug ENABLE_REWORKED_DATA_AGGREGATION_PAGES=true
Run dp-design-system
Port forward the api router to sandbox dp ssh sandbox web 1 -p 23200:localhost:10800
Pages:

https://dp.aws.onsdigital.uk/datalist
https://dp.aws.onsdigital.uk/publications

Toggle content type filters, refresh
Sense check.

### Who can review

Frontend

2024-04-08 11:46 UTC, lindenmckenzie requested changes
Have not reviewed the code. 

Item one:

> On /publications checking all filters, starting with 'Statistical bulletins', will only filter to 'bulletins` and have 4514 rather than the expected 7475

On this, it's because the `dp-search-api` is expecting the `content_type` param to be one param not multiples. This is not a change you've introduced :) 

Have a look into it and see whether you think we should add it to the scope of this ticket or add a new one. Whether we correct it here or in the api is something you should think about too. 

> Checking 'Compendiums' doesn't do anything, in the chrome network tab, it's causing a 500 error

Log from the search API is "content type(s) not allowed" - think it should be a `compendium_landing_page`

This is down to where you're setting the value in the input field. Because of item 1, it gets ignored when it's not on it's own.

2024-04-08 11:46 UTC, lindenmckenzie commented on assets/templates/partials/data-filters/single-content-type-filter.tmpl
> +                                    value="{{ $id }}"
this is the one that's tripping up the compendia I'd guess.

2024-04-10 11:56 UTC, StRhys commented
After lots of trials and missteps, I found the issue, a missing function which changed the filters into the corresponding content_types. Was on the search query but not the aggregation query. So this sorts both issues!

One issue I have spotted though is on `/datalist`, the `datasets` filter shows two different results, 4287 for the filter, but 4282 for the total. See image below. The `datasets` filter only has two content_types, being `dataset_landing_page` and `timeseries_dataset` and looking at the api, these only return 4282. From what I can see when getting the filters/counts it's only fetching the results for `dataset_landing_page` and `timeseries_dataset`, which is returning the 4287, so unsure where these extra 5 for the filter are coming from.

![image](https://github.com/ONSdigital/dp-frontend-search-controller/assets/110108574/fd60acf6-0ed7-43a6-b964-7ea2c6b9c689)

2024-04-12 11:41 UTC, mr-nick17 reviewed
Tested and looks good 👍. Minor markup comment

2024-04-12 12:33 UTC, mr-nick17 approved these changes

2024-04-15 08:02 UTC, lindenmckenzie approved these changes

2024-04-15 08:41 UTC, merged