allow 3rd level subtopics
ONSdigital/dp-frontend-search-controller pull request #323
Opened 2024-06-04 00:04 UTC by Oluwawunmi

### What

Refactor aggregated data subtopic pages to allow multi level subtopics
[Trello Card](https://trello.com/c/9HgeOu40/2177-refactor-aggregated-data-subtopic-pages-to-allow-3rd-level-subtopics)

### How to review

- Check code is ok
- Pull branch
- set EnableReworkedDataAggregationPages to 'true'
- run application and try accessing a route with topic, subtopic and subsubtopic in its url from your browser
- Ensure correct data is displayed and cache working.

### Who can review

Anyone

2024-06-04 14:30 UTC, lindenmckenzie requested changes
Looks pretty good - have looked at code and tested some of it locally, some points:
- 3rd level unit / component testing would be good. 
- not sure about 'remainingPath'
- I'm not sure if this change has introduced this, but it's firing 1200+ requests to the topic API on startup. Given there's about 50 topics, that seems a bit heavy handed.

2024-06-04 14:30 UTC, lindenmckenzie commented on routes/routes.go
> +		r.StrictSlash(true).Path("/{remainingPath:.*}/topicspecificmethodology").Methods("GET").HandlerFunc(handlers.ReadDataAggregationWithTopics(cfg, hc, cacheList, "home-methodology"))
`remainingPath` makes it sound like it's the tail end of the path, not sure about this name.

2024-06-04 14:30 UTC, lindenmckenzie commented on cache/public/public_topic.go
> +			log.Error(ctx, "no sub topics found for "+dataTopicCache.ID+" from topic-api", err, logData)
we try not to use dynamic log lines - better to store it in the data block.

2024-06-11 13:13 UTC, lindenmckenzie requested changes

2024-06-11 13:13 UTC, lindenmckenzie commented on cache/private/private_topic.go
> +		rootTopics, err := topicClient.GetTopicPrivate(ctx, topicCli.Headers{}, cache.RootTopicID)
You still need to pass the ServiceAuthToken here.

2024-06-11 13:13 UTC, lindenmckenzie commented on cache/private/private_topic.go
> +		rootTopics, err := topicClient.GetTopicPrivate(ctx, topicCli.Headers{}, cache.RootTopicID)
Recommend testing this running in publishing mode, testing against the publishing mount.

2024-06-11 13:13 UTC, lindenmckenzie commented on cache/private/private_topic.go
> +		rootTopics, err := topicClient.GetTopicPrivate(ctx, topicCli.Headers{}, cache.RootTopicID)
I'm not sure this comment is true either anymore. Or that you retrieve rootTopics - you're retrieving the rootTopic no?

2024-06-11 13:13 UTC, lindenmckenzie commented on cache/public/public_topic.go
>  			return []*cache.Topic{cache.GetEmptyTopic()}
This block is no longer accurate as well.

2024-06-11 13:13 UTC, lindenmckenzie commented on data/topic_filter.go
>  	}
Why this change? linting?

2024-06-11 13:13 UTC, lindenmckenzie commented on features/steps/steps.go
> +	//topicID := "6646"
Why leaving the comment in?

2024-06-11 13:13 UTC, lindenmckenzie commented on handlers/handlers_test.go
> +				}
I think I put in a function that deals with getting the right search call?

2024-06-11 13:13 UTC, lindenmckenzie commented on routes/routes.go
> +		if cfg.EnableTopicAggregationPages {
If this is a combination feature flag then please note this in the readme.

2024-06-11 13:13 UTC, lindenmckenzie commented on service/service.go
> +		if svc.Config.EnableTopicAggregationPages {
why svc.Config and not cfg. direct?

2024-06-11 13:13 UTC, lindenmckenzie commented on service/service.go
> +		if svc.Config.EnableTopicAggregationPages {
Same question

2024-06-11 13:13 UTC, lindenmckenzie commented on service/service.go
> +	if svc.Config.EnableTopicAggregationPages {
Same question.

2024-06-11 13:13 UTC, lindenmckenzie commented on service/service.go
> +		if svc.Config.EnableTopicAggregationPages {
Same question.

2024-06-11 13:13 UTC, lindenmckenzie commented on config/config.go
> +	EnableTopicAggregationPages             bool          `envconfig:"ENABLE_TOPIC_AGGREGATION_PAGES"`
There should be units tests for this.

2024-06-11 13:13 UTC, lindenmckenzie commented on service/service.go
> +		if svc.Config.EnableTopicAggregationPages {
I would suggest a component level test to ensure no requests go to the Topic API if it's switched off. Or I guess maybe only to the root topic. Something to think about. Not dead set on it.

2024-06-11 14:28 UTC, Oluwawunmi commented on README.md
> +| ENABLE_AGGREGATION_PAGES                    | false                           | Enable the aggregation pages                                                                                       |
The plan is add the new flags first all the way up to prod, then come back to delete the old flag all the way up after deployment.

2024-06-12 16:32 UTC, lindenmckenzie reviewed
Exceptionally pedantic comments.

2024-06-12 16:32 UTC, lindenmckenzie commented on cache/private/private_topic.go
> +		// subtopicsChan := make(chan models.Topic)
Why commented out?

2024-06-12 16:32 UTC, lindenmckenzie commented on cache/public/public_topic.go
> +		// subtopicsChan := make(chan models.Topic)
Why commented out?

2024-06-12 16:32 UTC, lindenmckenzie commented on README.md
> +| ENABLE_TOPIC_AGGREGATION_PAGES              | false                           | Enable the topic aggregation pages, is a combination feature flag with ENABLE_AGGREGATION_PAGES                    |
So just be clear here that to enable the topic ones you have to enable the aggregation pages as well.

2024-06-13 12:52 UTC, lindenmckenzie approved these changes

2024-06-13 16:50 UTC, lindenmckenzie approved these changes

2024-06-14 08:43 UTC, merged